#
# email and level are required for users
#
users:
  - email: <%= ENV.fetch("ADMIN_EMAIL", "admin@barong.io") %>
    password: <%= ENV.fetch("ADMIN_PASSWORD", nil) %>
    role: "admin"
    state: "active"
    level: 3

levels:
  - key: email
    value: verified
    description: "User clicked on the confirmation link"
  - key: phone
    value: verified
    description: "User entered a valid code from sms"
  - key: document
    value: verified
    description: "User personal documents have been verified"
